// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnwlxjzypfrpfqamwzrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFud2x4anp5cGZycGZxYW13enJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjE1MjMsImV4cCI6MjA2MzgzNzUyM30.Fq2JpldbUGg9BThbQjiZKg5J6CsSLETvWQcqgsvr0Zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);